# Generated by Django 5.2.9 on 2026-03-12 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('loan_inci_expn', models.TextField(blank=True, null=True)),
                ('erly_rpay_fee', models.TextField(blank=True, null=True)),
                ('dly_rate', models.TextField(blank=True, null=True)),
                ('loan_lmt', models.TextField(blank=True, null=True)),
                ('search_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MortgageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('mrtg_type_nm', models.CharField(max_length=100)),
                ('rpay_type_nm', models.CharField(max_length=100)),
                ('lend_rate_type_nm', models.CharField(max_length=100)),
                ('lend_rate_min', models.FloatField(null=True)),
                ('lend_rate_max', models.FloatField(null=True)),
                ('lend_rate_avg', models.FloatField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.mortgageloan')),
            ],
        ),
    ]
