# Generated by Django 5.2.9 on 2026-03-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MortgageLoan',
            new_name='MortgageBaseInfo',
        ),
    ]
