# Generated by Django 5.2.9 on 2026-03-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mortgagebaseinfo_lend_rate_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgagebaseinfo',
            name='rpay_type_nm',
            field=models.CharField(max_length=100),
        ),
    ]
