# Generated by Django 5.2.12 on 2026-03-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_mortgagebaseinfo_rpay_type_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagebaseinfo',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
