# Generated by Django 5.2.12 on 2026-03-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_mortgagebaseinfo_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagebaseinfo',
            name='combined_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
