# Generated by Django 5.2.12 on 2026-03-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_mortgagebaseinfo_combined_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagebaseinfo',
            name='combined_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
