# Generated by Django 5.2.12 on 2026-03-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_mortgagebaseinfo_combined_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLoanBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_no', models.CharField(max_length=20)),
                ('kor_co_nm', models.CharField(max_length=50)),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.TextField()),
                ('crdt_prdt_type', models.CharField(max_length=10)),
                ('crdt_prdt_type_nm', models.CharField(max_length=50)),
                ('cb_name', models.CharField(max_length=50)),
                ('dcls_strt_day', models.CharField(max_length=8)),
                ('dcls_end_day', models.CharField(blank=True, max_length=8, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=14)),
                ('crdt_lend_rate_type', models.CharField(max_length=10)),
                ('crdt_lend_rate_type_nm', models.CharField(max_length=50)),
                ('crdt_grad_1', models.FloatField(null=True)),
                ('crdt_grad_4', models.FloatField(null=True)),
                ('crdt_grad_5', models.FloatField(null=True)),
                ('crdt_grad_6', models.FloatField(null=True)),
                ('crdt_grad_10', models.FloatField(null=True)),
                ('crdt_grad_11', models.FloatField(null=True)),
                ('crdt_grad_12', models.FloatField(null=True)),
                ('crdt_grad_13', models.FloatField(null=True)),
                ('crdt_grad_avg', models.FloatField(null=True)),
                ('search_content', models.TextField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('combined_content', models.TextField(blank=True, null=True)),
                ('combined_embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
