# Generated by Django 5.2.12 on 2026-03-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_creditloanbaseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagebaseinfo',
            name='erly_rpay_fee_float',
            field=models.FloatField(null=True),
        ),
    ]
