# Generated by Django 5.2.12 on 2026-03-20 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_mortgagebaseinfo_erly_rpay_fee_float'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditLoanBaseInfo',
        ),
    ]
