# Generated by Django 5.2.12 on 2026-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_creditloanbaseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', models.BinaryField()),
                ('chapter_title', models.CharField(max_length=200, null=True)),
                ('page_number', models.IntegerField(null=True)),
            ],
        ),
    ]
