# Generated by Django 5.2.12 on 2026-04-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_manualchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualchunk',
            name='page_number',
        ),
        migrations.AddField(
            model_name='manualchunk',
            name='combined_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
