# Generated by Django 5.2.12 on 2026-04-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_manualchunk_page_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualchunk',
            name='embedding_chapter_title',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
