# Generated by Django 5.2.9 on 2026-03-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_mortgageloan_mortgagebaseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagebaseinfo',
            name='lend_rate_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mortgagebaseinfo',
            name='lend_rate_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mortgagebaseinfo',
            name='lend_rate_type_nm',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mortgagebaseinfo',
            name='mrtg_type_nm',
            field=models.CharField(default='아파트', max_length=100),
        ),
        migrations.AddField(
            model_name='mortgagebaseinfo',
            name='rpay_type_nm',
            field=models.CharField(default='원리금분할상환', max_length=100),
        ),
        migrations.DeleteModel(
            name='MortgageOption',
        ),
    ]
